### ISSUE TITLE
某类文章格式抓取错误。但没有提示。

### ISSUE THREAD

**Issue by fantaxy025025** [systemmin/wxdown#11]
像这类文章格式，抓取错误。
https://mp.weixin.qq.com/s/FDHJqtVZ5PEHvtH-jDFZgA

**Comment by systemmin** [comment]
下个版本更新

**Comment by systemmin** [comment]
这不是可以吗？？，你看你的软件是不是最新版的，不是更新一下

![image](https://github.com/user-attachments/assets/eeb30855-abe6-40d3-9810-3127066a7eb7)
