### ISSUE TITLE
在使用中发现的一些问题

### ISSUE THREAD

**Issue by The3ight** [systemmin/wxdown#12]
1、大批量下载时 会有部分html没有成功下载 同时也不太好看出来是哪个没下载下来
2、下载下来的文件名 会丢失空格 导致一些英文会连到一块儿 
3、如果能监听剪切板 就更好了 
4、不支持 https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzAwMjU0MjIyNw== 这种公众号所有文章下载

**Comment by systemmin** [comment]
1. 这个问题，你对比一下你传入的链接数量和下载文件数量，才能确认是否有漏的。公众号目录下有 `db` 目录中 `db.jsonl` 文件有记录下载链接。如果是合集下载 `data/task` 下记录下载链接
3. 这个下个版本处理一下
4. 接受建议
5. 不支持获取公众号历史文章

**Comment by The3ight** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by systemmin** [comment]
更新1.0.8
