### ISSUE TITLE
对于内嵌的视频号视频是否可以支持？

### ISSUE THREAD

**Issue by prettystone** [systemmin/wxdown#3]
### 如图（https://mp.weixin.qq.com/s/ufhGZLT8m9wE8rIwD8mt-A）

![image](https://github.com/systemmin/wxdown/assets/9128549/d21ec0b4-49d6-4c39-a181-2072ac2af66b)

**Comment by systemmin** [comment]
目前还不支持，看后面能不能想办法支持下

你也可以看下这个仓库好像可以 https://github.com/qiye45/wechatVideoDownload.git
