### ISSUE TITLE
有些公众号tag采集报错

### ISSUE THREAD

**Issue by aexiaosong** [systemmin/wxdown#4]
采集地址：https://mp.weixin.qq.com/mp/appmsgalbum?__biz=Mzg2MjU4MTExNw==&action=getalbum&album_id=2905030758938165252&scene=173&subscene=&sessionid=undefined&enterid=0&from_msgid=2247483911&from_itemidx=1&count=3&nolastread=1#wechat_redirect

![image](https://github.com/user-attachments/assets/c6db29df-9275-410e-8392-89b7755f3a65)

**Comment by systemmin** [comment]
ok

**Comment by systemmin** [comment]
更新1.0.4
