### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by yangzcy** [systemmin/wxdown#6]
windows上，软件安装后第一次使用成功了，之后启动winxdown.exe，dos窗口一直闪退，无法进入程序。

**Comment by yangzcy** [comment]
补充说明，注销win用户，重启电脑都尝试了，不管用

**Comment by yangzcy** [comment]
补充说明，重启电脑，注销用户均不管用。刚刚重装，发现可以了，汗啊~

**Comment by systemmin** [comment]
> windows上，软件安装后第一次使用成功了，之后启动winxdown.exe，dos窗口一直闪退，无法进入程序。

在 cmd 窗口执行 wxdown.exe 试试，看出现什么错我，不要双击打开
