### ISSUE TITLE
目录下拉选择，无反应

### ISSUE THREAD

**Issue by unnormalcow** [systemmin/wxdown#9]
目录下拉选择，无反应

**Comment by unnormalcow** [comment]
> 目录下拉选择，无反应

确切说，Edge浏览器，无反应，实测Chrome是可以的

**Comment by systemmin** [comment]
![image](https://github.com/user-attachments/assets/aee5f54c-4b68-4637-b74b-d086a3a1a77e)


不能够啊，我的edge可以

**Comment by systemmin** [comment]
F5 刷新页面试试，这个input框的选择都标准的HTML元素 [datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist)
